services:
  postgres:
    image: postgres:16-alpine
    container_name: commissionpro_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commissionpro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: commissionpro_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/commissionpro"
      DEFAULT_COMMISSION_RATE: 5
      STORAGE_DRIVER: "local"
      LOCAL_STORAGE_PATH: "./storage/contrats"
      AES_ENCRYPTION_KEY: "cdb5e14891371230226ea554da83c5de0f9c4fb8904d7e6c62f25016a37e28f6"
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

volumes:
  postgres_data:
  mk42_node_modules:
