FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 3000
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true

CMD ["sh", "-c", "npx prisma generate && npm run dev -- --hostname 0.0.0.0"]
