FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install && npm install lightningcss-linux-x64-musl

EXPOSE 3000
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true

CMD sh -c "npx prisma generate && npm run dev -- --hostname 0.0.0.0"
